---
title: "2.1 — Production, Specialization, and Firms — Class Content"
draft: false
linktitle: "2.1 — Production, Specialization, & Firms"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 8
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "2.1-slides"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F,
                      message=F,
                      warning=F,
                      fig.retina = 3,
                      fig.align="center")
library("tidyverse")
library("ggrepel")
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
update_geom_defaults("text", list(family = "Fira Sans Condensed"))
```

{{% alert note %}}
*Wednesday, September 29, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we start looking on the supply side of the market for the next few weeks. You will ultimately see, we will use the same tools (and get basically the same results!) for studying producers (constrained optimization models) as we did for consumers. Sometimes, these models finally "click" for students the second time around, and production is often more intuitive than utility and consumption.

Today we set up the problem, and discuss what it is that firms do. If you want to learn a lot more about the economics of organization and theory of the firm, see my [Industrial Organization class](https://ios20.classes.ryansafner.com).

In the beginning, I introduce the canonical model of comparative advantage as a way to explore a lot of insights about production, the division of labor, specialization and trade, and the theory of the firm. Do not get too distracted in the graphs or mechanics of this model (though it should echo things that we have seen before), it is only a useful segue for what we will cover in the next 2-3 weeks. If you want to know more, I do a deep dive with these models to explain [international trade in ECON 324](https://tradef20.classes.ryansafner.com).

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 14.4 (on the production possibilities frontier), 6.1 in Goolsbee, Levitt, and Syverson, 2019

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-laptop-code"></i> Assignments