---
title: "2.7 — External Economies and Industry Supply — Class Content"
draft: false
linktitle: "2.7 — External Economies and Industry Supply"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 14
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "2.7-slides"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F,
                      message=F,
                      warning=F,
                      fig.retina = 3,
                      fig.align="center")
library("tidyverse")
library("ggrepel")
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
update_geom_defaults("text", list(family = "Fira Sans Condensed"))
```

{{% alert note %}}
*Wednesday, March 30, 2022*
{{% /alert %}}

{{% alert warning %}}
[Problem Set 4](/assignments/04-problem-set) is due by the end of the day Friday April 1.

[Exam 2](/assignments/02-exam) will be on Monday April 4. 
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

We wrap up Unit 2 on today by discussing **external economies**, which are cost externalities within an entire industry, but we will be skipping this for time. I put my slides here if you want to know more. The idea is firms entering/exiting a profitable/unprofitable industry over the long run certainly shift the industry supply curve and change the market equilibrium. But in a lot of industries as more firms enter and produce and compete with one another, that might raise costs for *all firms* (increasing cost industry/external diseconomies) or lower costs for *all firms* (decreasing cost industry/external economies). These effects may create either an upward sloping, flat, or downward sloping industry supply curve over the long run.

We also end by looking at market supply functions, allowing us to fully transition into Unit III with Supply & Demand. 

After a short lecture on 2.7 today, we will have a **review session** for [**Exam 2**](/assignments/02-exam), which will on Monday April 4.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Chs. 8.5, 2.5 in Goolsbee, Levitt, and Syverson, 2019

Chapter 2.5 is from the chapter on Supply & Demand, on the supply curve.

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-laptop-code"></i> Assignments

## Problem Set 4 Due Fri Apr 1

[Problem set 4](/assignments/04-problem-set) (on classes 2.4-2.6) is due by the end of the day Friday, April 1 by upload to Blackboard Assignments.