---
title: "3.1 — The Supply and Demand Model — Class Content"
draft: false
linktitle: "3.1 — Supply and Demand"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 14
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.1-slides"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F,
                      message=F,
                      warning=F,
                      fig.retina = 3,
                      fig.align="center")
library("tidyverse")
library("ggrepel")
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
update_geom_defaults("text", list(family = "Fira Sans Condensed"))
```

{{% alert note %}}
*Monday, November 1, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we bring supply and demand together to talk about equilibrium, and begin to discuss how markets work in the real world. In doing so, we will run a demonstration in class using the [kiviq](kiviq.us) software ([see instructions here](/slides/using-kiviq.pdf)).

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 3 in Goolsbee, Levitt, and Syverson, 2019

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`