---
title: "4.4 — Monopolistic Competition and Oligopoly — Class Content"
draft: false
linktitle: "4.4 — Monopolistic Competition and Oligopoly"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 18
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.4-slides"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F,
                      message=F,
                      warning=F,
                      fig.retina = 3,
                      fig.align="center")
library("tidyverse")
library("ggrepel")
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
update_geom_defaults("text", list(family = "Fira Sans Condensed"))
```

{{% alert note %}}
*Monday November 29, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we finally return to finish our tour of industrial organization, i.e. the types of markets by competitiveness. 

We first cover **monopolistic competition**, a much more realistic model of most firms in the real world, where firms have some market power, but are not the only producer in their industry. To model them, we blend elements of *monopoly* with elements of *perfect competition*. In the short-run, we model the firm as a monopoly acting like any monopolist would, but in the long run, there is **free entry and exit**, so other entrants reduce the demand for any one firm’s product (and make it more elastic) so that firms’ economic profits go to zero.

We finally cover **oligopoly**, where there are a small number of firms with market power that **interact strategically**. While some industries in the real world are indeed dominated by a small number of firms, this type of model is applicable well beyond industries with a small number of firms, as to understand the strategic nature of firm decisions, we introduce **game theory** into our models. 

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fas fa-book"></i> Ch. 11 in Goolsbee, Levitt, and Syverson, 2019

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`
