---
title: "4.5 — Game Theory, Contestable Markets & Wrap Up — Class Content"
draft: false
linktitle: "4.5 — Game Theory, Contestable Markets & Wrap Up"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 19
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.5-slides"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F,
                      message=F,
                      warning=F,
                      fig.retina = 3,
                      fig.align="center")
library("tidyverse")
library("ggrepel")
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
update_geom_defaults("text", list(family = "Fira Sans Condensed"))
```

{{% alert note %}}
*Monday May 9, 2022*
{{% /alert %}}

{{% alert warning %}}
[Op-ed](/assignments/op-ed) is due by the end of the day Monday May 9 by upload to Chalk-and-Wire (via Blackboard), with a word count!

[Final Exam](/assignment/03-exam) will be in our classroom at 11:30am-2:00pm on Friday May 13.
{{% /alert %}}


## <i class="fas fa-info-circle fa-lg"></i> Overview
 
We wrap up today by discussing some more about game theory (beyond mere prisoners' dilemmas), and apply these insights in general to market competition by considering one final model of a **contestable market**. Then we will wrap up and summarize the semester before reviewing for the final exam. 

## <i class="fas fa-book-reader fa-lg"></i> Readings

### Recommended Readings

- [<i class="fas fa-file-pdf"></i> Baumol, William, 1982, [“Contestable Markets: An Uprising in the Theory of Industry Structure”](/readings/Baumol-1982.pdf)
- <i class="fas fa-file-pdf"></i> Hayek, Friedrich A, 1948, [“The Meaning of Competition”](https://mises.org/library/meaning-competition), Chapter V in *Individualism and Economic Order*
- <i class="fas fas fa-book"></i> Kirzner, Israel M, 1973, [*Competition and Entrepreneurship*](http://www.sjsu.edu/people/john.estill/courses/158-s15/Israel%20Kirzner%20-%20Competition%20And%20Entrepreneurship.pdf)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`
