---
title: "Final Exam"
draft: false
linktitle: "Final Exam"
date: "2020-06-08"
menu:
  assignments:
    parent: Exams
    weight: 5
type: docs
#output:
#  blogdown::html_page:
#    toc: true
---

{{% alert note %}}
Monday, December 13 (11:30 AM — 2:00 PM) on Blackboard Assignments, [as per the Registrar](https://www.hood.edu/offices-services/registrars-office/academic-calendar/final-exam-schedule)
{{% /alert %}}

# Exam Information

The Final Exam will be held **on Blackboard assignments** from **11:30AM—2:00PM** on **Monday December 13**.

The exam will be a **timed assignment**. You will *not* need the whole time, I have designed the test to give you some extra time to accommodate the technical difficulties of taking an exam at home. You may close the exam page and come back to it, but *the timer will continue to run* once the exam is first opened.

If you have any approved testing accommodations, or know in advance you must be absent, please confirm with me ASAP and we will make arrangements

While the exam is out, neither the TA nor I will answer any questions. The one exception is, **email/message me ASAP if you encounter technical problems**.

# Exam Instructions (<i class="fas fa-exclamation-circle"></i> Important, Please read)

This exam will be **open-book/website, open-notes**, but **do not use the internet, or contact others**. [I have designed the exam so that Google won't help you. Everything you need should be in your notes, homeworks, or slides anyway.] I will automatically interpret substantially-similar answers, obviously-googled answers, and contact between students as cheating or plagiarism, respectively. Either will earn you a 0, and be reported. Answers should be *in your own words*, I will also deduct points for blatant copy-pastes off my slides (those are *my* words, not yours!).

You must show all of your work (for calculation problems), either by typing your steps into the answer form, or you may upload handwritten steps to the exam, solving your problems. Only as a *last* resort (please!), you may email me your work before your time runs out.

It is more important to me that you spend your time working and writing the answers, and less about all the technology working flawlessly.

# Concepts Study Guide

- [<i class="fas fa-file-pdf"></i> Download PDF](/examprep/exam_3_study_guide.pdf)

# "Practice" Exam

- [<i class="fas fa-file-pdf"></i> Download Old Exam 2](/examprep/Exam3.pdf)
<!-- [<i class="far fa-life-ring"></i> Answer Key](/examprep/Exam2_Answer_Key.pdf)-->

Above, you have a previous semester's actual exam. Use it to get a sense of what questions are asked, the format, and how many. Note we skipped content that the first question covers (constant cost industries).

**Be aware: this is pre-Covid when exams were taken in person on paper. The online nature of this semester will significantly affect the questions asked!** Questions draw from topics in Unit 1, and note that **just because topics or questions were not in the practice exam does NOT mean they may not show up on your exam.**^[I hope that this is obvious. I write this to ensure there is no misunderstanding.] Aside from minor extensions, no mathematical problem on any exam should be something you have not seen in some form before. 

Look at the practice exam *before* our Review day. I will post the answer key during the weekend. I am happy to discuss other individual answers and strategies during Office Hours.

# My Advice

Make sure you do all of the homework problems and learn from the answer keys to the homeworks, as well as the in-class practice problems. All of the math problems are largely in the style of the homework questions. While some of the questions should be novel applications, conceptual questions on homeworks will get you in the right headspace to think about answering a question on an exam.^[The point of exams is to *apply* what you've learned, not to literally regurgitate it! Or, at least, it should be.]